### ISSUE TITLE
Prefix Configuration Issue on Windows

### ISSUE THREAD

**Issue by brunomenezes** [keymetrics/pm2-io-apm#121]
Hi Guys! 
I just installed the latest development version of pm2 3.0.0-alpha1 and I am not able to run any script in it because of the following error;

> 0|test     | Error: Cannot find module '..//package.json'
0|test     |     at Function.Module._resolveFilename (module.js:469:15)
0|test     |     at Function.Module._load (module.js:417:25)
0|test     |     at Module.require (module.js:497:17)
0|test     |     at require (internal/module.js:20:19)
0|test     |     at Object.<anonymous> (D:\somewhere\nodejs\node_modules\pm2\node_modules\@pm2\io\build\main\src\configuration.js:12:13)
0|test     |     at Module._compile (module.js:570:32)
0|test     |     at Object.Module._extensions..js (module.js:579:10)
0|test     |     at Module.load (module.js:487:32)
0|test     |     at tryModuleLoad (module.js:446:12)
0|test     |     at Function.Module._load (module.js:438:3)

The problem is in this [line](https://github.com/keymetrics/pm2-io-apm/blob/c0a55c0afcf44ae1b06be3665878e57099674a7a/src/configuration.ts#L10) when generating the right prefix to find the package.json. It is always executing the else on this ternary. A solution would be doing a simple replace before the indexOf like this: 

`__dirname.replace(/\\/g, '/').indexOf('/build/')`

It would not affect an unix environment but avoid problem on a windows environment. That is all related to the way windows path is described using the "\\". 

I hope I am opening the issue in the right place. I am following the bugs address in the package.json inside the pm2/io directory

. Thanks in advance.

**Comment by wallet77** [comment]
Fixed : https://github.com/keymetrics/pm2-io-apm/pull/122
Landed in 2.0.0-alpha30
