### ISSUE TITLE
This module vs. pmx

### ISSUE THREAD

**Issue by mmckelvy** [keymetrics/pm2-io-apm#129]
Hi guys!  First, really appreciate the work you guys are doing on this and pm2 generally.

I'm a Keymetrics subscriber.  I want to use a few of the advanced monitoring functions (e.g. emit events, track exceptions).  Am I supposed to use this module or the pmx module for that?

Thanks much.

**Comment by wallet77** [comment]
Hi @mmckelvy 

This module can be used with pm2 3.0.0 or higher.
This is a complete refactoring of pmx.

So until pm2 v3 is released you should use pmx.
