### ISSUE TITLE
io.scopedAction doesn't work

### ISSUE THREAD

**Issue by Cow258** [keymetrics/pm2-io-apm#143]
## Example Code to explain what i am going to do

```javascript
const pm2io = require('@pm2/io');
pm2io.scopedAction('Git Update', function (data, res) {
    const child = spawn('git', ['pull']);

    child.stdout.on('data', (chunk) => {
        chunk.toString().split('\n').forEach(function (line) {
            res.send(line); // This send log to Keymetrics to be saved (for tracking)
        });
    });

    child.stdout.on('end', (chunk) => {
        res.end('end'); // This end the scoped action
    });

    child.on('error', (e) => {
        res.error(e);  // This report an error to Keymetrics
    });
});
```

## Issue
No response on Keymetrics without any error.
The action has not been executed.

## Issue Screen Shot
Google Drive: [pm2IO_error.png](https://drive.google.com/file/d/1kCu1UqmmSMwMUyoPfVJDL4SZIIH11Pv8/view?usp=sharing)

## Expected
Showing up console line and getting response.
Action is executed.

## Expected Screen Shot
Google Drive: [pm2_expected.png](https://drive.google.com/file/d/1kCu1UqmmSMwMUyoPfVJDL4SZIIH11Pv8/view?usp=sharing)

## Issue Version
**@pm2/io**

^2.0.3

**pm2 -v**

3.0.0

**node -v**

10.6.0

**npm -v**

6.10

## Old server version
**pmx**

^1.6.4

**pm2 -v**

2.10.4

**node -v**

8.11.2

**npm -v**

6.10

**Comment by Cow258** [comment]
@wallet77 Please take a look, Thank you.

**Comment by wallet77** [comment]
@Cow258 

I will.
I'm fixing an important issue about closing listener in apm and then I will work on this issue.
There are some test on scoped action, I think "basic" scoped action are working. But maybe an issue with spawn.

**Comment by wallet77** [comment]
Hi @Cow258 

I've just tested with unit and integration tests with your example and it works.
I will with pm2 to see if there is an impact.

**Comment by Eywek** [comment]
Hi @Cow258 can you send us the pm2-io-agent's log file ? (should be here `~/.pm2/agent.log`)
