### ISSUE TITLE
global._metrics.var_count

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#144]
Idea

To facilitate the exposure of variables as metrics to pm2 plus, a special global variable could be monitored by pm2/io, let's say global._metrics. This variable would be iterated by the ProcessContainer's @pm2/io and directly expose metrics as custom metrics

**Comment by wallet77** [comment]
Great idea.

We can also set the property name in io config, so wouldn't have to hard code _metrics.

```
io.init({
  customMetrics: "_metrics"
})
```

**Comment by Unitech** [comment]
or we could have

```
global._metrics
global._histogram
global._meter
....
```
