### ISSUE TITLE
Wrap child_process to monitor the number of fork currently managed by app

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#160]
Wrap spawn, fork to monitor the count of forked application. It could be a automatic metrics like the one we provide with app metrics

**Comment by Unitech** [comment]
And also monitor the number of threads https://github.com/keymetrics/pm2-io-apm/issues/139

**Comment by wallet77** [comment]
Done here : https://github.com/keymetrics/pm2-io-apm/pull/168
