### ISSUE TITLE
npm http fetch GET 404 https://registry.npmjs.org/@pm2%2fio

### ISSUE THREAD

**Issue by sirisian** [keymetrics/pm2-io-apm#167]
When I tried to install pm2 it failed on pm2/io getting the dependency. All the other dependencies downloaded fine. This is on a fresh node.js install. Just installing pm2/io by itself fails for this one server. Has anyone seen this behavior before? I don't know why this specific package isn't working.

npm@5.6.0 and node@v8.11.3

> npm install @pm2/io --save --verbose
> npm info it worked if it ends with ok
> npm verb cli [ '/usr/bin/node',
> npm verb cli   '/usr/bin/npm',
> npm verb cli   'install',
> npm verb cli   '@pm2/io',
> npm verb cli   '--save',
> npm verb cli   '--verbose' ]
> npm info using npm@5.6.0
> npm info using node@v8.11.3
> npm verb npm-session 4756b691f3fb639d
> npm http fetch GET 404 https://registry.npmjs.org/@pm2%2fio 815ms
> npm verb stack Error: 404 Not Found: @pm2/io@latest
> npm verb stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
> npm verb stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> npm verb stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
> npm verb stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> npm verb stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> npm verb stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
> npm verb stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
> npm verb stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
> npm verb stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
> npm verb stack     at runCallback (timers.js:810:20)
> npm verb stack     at tryOnImmediate (timers.js:768:5)
> npm verb stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
> npm verb cwd /tmp
> npm verb Linux 4.4.0-130-generic
> npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "@pm2/io" "--save" "--verbose"
> npm verb node v8.11.3
> npm verb npm  v5.6.0
> npm ERR! code E404
> npm ERR! 404 Not Found: @pm2/io@latest
> npm verb exit [ 1, true ]

npm config set @pm2:registry https://registry.npmjs.org/

Should that command fix this? It doesn't for me. Still 404.

**Comment by sirisian** [comment]
Nevermind. I just uninstalled node, npm, and cleared the cache for npm manually and it worked again.

**Comment by sharabiania** [comment]
Clearing the cache did not solve my issue. Still getting the same error as yours.
