### ISSUE TITLE
@pm2/io typings empty

### ISSUE THREAD

**Issue by eyyubovkamran** [keymetrics/pm2-io-apm#171]
I'm using typescript and installed @pm2/io with npm. But when I look at the typings in `node_modules/@pm2/io/build/main/src/index.d.ts` it is just `export {};`  Where can I find proper typings?

**Comment by wallet77** [comment]
Hi @eyyubovkamran 

I will take a look but I'm pretty sure we don't generate proper typings for now.
I will fix it as soon as possible.

**Comment by wallet77** [comment]
Done here : https://github.com/keymetrics/pm2-io-apm/pull/173

Waiting for release.
