### ISSUE TITLE
Couldn't find any versions for "@pm2/io" that matches "2.3.11"

### ISSUE THREAD

**Issue by manikumarrepuri** [keymetrics/pm2-io-apm#195]
The only latest version I could see is 2.1.2.

This happens even with the 2.3.9 as well

**Comment by Unitech** [comment]
2.3.11 has been 3 days ago: https://www.npmjs.com/package/@pm2/io

**Comment by manikumarrepuri** [comment]
Below is the response if i try to install the specific version which is latest.
![image](https://user-images.githubusercontent.com/20675532/45318416-cf8f4500-b534-11e8-820b-c398decbf58f.png)


If I don't give any version and just say @latest it installs 2.1.2

**Comment by wallet77** [comment]
It's clearly a problem with your system or your cache : 
![screenshot from 2018-09-11 09-59-53](https://user-images.githubusercontent.com/5022887/45346587-dad08800-b5a9-11e8-97e8-475d3107fcac.png)
