### ISSUE TITLE
Performance overhead compared to appmetrics package

### ISSUE THREAD

**Issue by gustavomassa** [keymetrics/pm2-io-apm#200]
Hello,

I see that you are using your own metric packages like the "event-loop-inspector", but how is performance overhead compared to the appmetrics package?
https://github.com/RuntimeTools/appmetrics

**Comment by wallet77** [comment]
Hi @gustavomassa 

We also used a package close to appmetrics called deepmetrics.
So in theory we should have the same overhead.

But what is interesting with pm2-io-apm is the configuration of the apm features you want to enable.
So you can use just a one or two metrics only (all the others are not initialized).
You can be sure you have the minimum impact on your production.

Furthermore, event-loop-inspector doesn't have any dependencies, it only use built-in methods and the code itself is really simple.
So once again the overhead should not be a problem.
