### ISSUE TITLE
Node engine requirement inconsistent

### ISSUE THREAD

**Issue by ruiiiijiiiiang** [keymetrics/pm2-io-apm#206]
Hi,

I've been trying to install pm2 on our production servers which are running node v6. I received the following error message:
`error @pm2/agent-node@1.0.5: The engine "node" is incompatible with this module. Expected version ">=8.0".`
Upon inspection I noticed that pm2/agent-node requires node engine >= 8. Since the home page of pm2 states that it only requires node version >= 4, is there any way you can change pm2/agent-node to be compatible with earlier node versions? Thank you very much.

**Comment by vmarchaud** [comment]
Thanks for the report, i'm working on a fix

**Comment by vmarchaud** [comment]
i published the version `2.4.5` which embed the version `1.0.6` of the agent that doesn't require node 8 (the requirement is now done at the apm level)
