### ISSUE TITLE
Installation error 404

### ISSUE THREAD

**Issue by MarvinVk** [keymetrics/pm2-io-apm#208]
I'm getting a 404 error when I run `npm install @pm2/io --save`
"404 Not Found: @pm2/io@latest"

node v9.4.0
npm 6.4.1

I tried clearing my npm cache but no luck.

Any suggestions?

**Comment by vmarchaud** [comment]
I believe the problem comes from npm, the version are available : https://www.npmjs.com/package/@pm2/io
