### ISSUE TITLE
Docs are not correct for latest version

### ISSUE THREAD

**Issue by Jivings** [keymetrics/pm2-io-apm#217]
The [docs](https://pm2.io/doc/en/plus/guide/configuration/#expose-custom-metrics) on pm2.io are showing an old version of the library. 

I tried to implement a counter using code from the docs;

```
const Current_req_processed = io.metric({
  name: 'Current req processed',
  type: 'counter',
});
```

But the actual code to get a counter working was;

```
const Current_req_processed = io.counter({
  name: 'Current req processed'
});
```

The same was true of all the other custom metrics. Using code from the README of this repository was great.

**Comment by vmarchaud** [comment]
Bug is the same as https://github.com/keymetrics/pm2-io-apm/issues/209
I'm working on a new version that will fix the issue and i will update the docs after publishing it.
You can try it out using `@pm2/io@alpha` (still in alpha so shouldn't be put in prod)

**Comment by vmarchaud** [comment]
Both should be working with the newest version (3.0.0)
