### ISSUE TITLE
Error: Failed to require the profiler via addon, disabling profiling ...

### ISSUE THREAD

**Issue by bazineta** [keymetrics/pm2-io-apm#220]
Moving from 2.4.7 to 3.0.0 causes the following message to be emitted on startup.

`Failed to require the profiler via addon, disabling profiling ...`

This shows up when running as a standalone agent, i.e., not running under pm2, but rather just starting our node process standalone for development testing. Node version is 8.12.0.

There does not seem to be any migration documentation from 2.x to 3.x that I can find, and what documentation there was seems to be greatly abbreviated, for example, there's no longer any mention of the `expressErrorHandler`, so it's unclear as to what, if any, changes we should be making to effect the migration.

**Comment by vmarchaud** [comment]
I will add a notes in the readme about the upgrade from 2.x to 3.x and explain what is the message about asap

**Comment by vmarchaud** [comment]
I've added an quick guide to explain breaking changes from 2.x to 3.x (https://github.com/keymetrics/pm2-io-apm#2x-to-3x), i've also added documentation about `expressErrorHandler` there : https://github.com/keymetrics/pm2-io-apm#express-error-reporting

**Comment by bazineta** [comment]
Thanks.
