### ISSUE TITLE
Wrapping issues

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#235]
https://github.com/Unitech/pm2/issues/4201
https://github.com/Unitech/pm2/issues/4206
https://github.com/Unitech/pm2/issues/4199

cc @vmarchaud

**Comment by vmarchaud** [comment]
upstream PR: https://github.com/census-instrumentation/opencensus-node/pull/435

**Comment by vmarchaud** [comment]
Should be fixed with https://github.com/keymetrics/pm2-io-apm/releases/tag/4.1.3
