### ISSUE TITLE
Postgresql tracing via sequelize does not work

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#245]
sequelize@^4.31.2

**Comment by vmarchaud** [comment]
Do the code use promises and/or connection pooling ?

**Comment by Unitech** [comment]
no idea, you can ping the email I fowarded to you

**Comment by anujkalka** [comment]
Yes. we use promises and connection pooling.
Let me know if you need more information

**Comment by Unitech** [comment]
Can we close this since a PR was made to address this issue?

**Comment by anujkalka** [comment]
Yes, please proceed
