### ISSUE TITLE
Ignore warning from chrome extension

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#249]
`https://app.pm2.io/bucket/57e803fb753a1ef4c3e1b5fd/frontend/issues/74967df687b22fc5b7954efdb7631fbb?app=Production%20Front-end%20app.pm2.io chrome-extension://mpbpobfflnpcgagjijhmgnchggcjblin/content.js:4:19`

e.g.

https://app.pm2.io/bucket/57e803fb753a1ef4c3e1b5fd/frontend/issues/c286b03b032a5bfc6ca6d293c02a6b5c?app=Production%20Front-end%20app.pm2.io&filterCategory=ux-warning

https://app.pm2.io/bucket/57e803fb753a1ef4c3e1b5fd/frontend/issues/7af1b99e8e6f38bd6119978b39ef66b9?app=Production%20Front-end%20app.pm2.io&filterCategory=ux-warning

**Comment by Eywek** [comment]
https://github.com/keymetrics/pm2-io-apm-browser/issues/6
