### ISSUE TITLE
HTTP req/min is corrupted when turning the transaction tracing on

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#251]
Looks like the transaction tracing override change the behavior of the HTTP req/min.
HTTP: https://github.com/keymetrics/pm2-io-apm/blob/master/src/metrics/httpMetrics.ts#L81
HTTPS: https://github.com/keymetrics/pm2-io-apm/blob/master/src/metrics/httpMetrics.ts#L120

**Comment by Eywek** [comment]
v4.2.1 should fix that

**Comment by rchl** [comment]
@Eywek I don't understand code of this project but I have reasons to believe it caused some leak that causes app memory and cpu usage go up.

To reproduce this locally, I need to trigger about 100 000 requests to an app and then I'll see app using about 5% of CPU constantly. Might seem like nothing but in production, on worse machines, it's worse and also production I can have 1 million of requests per day so it's much more noticeable.

If it's false alarm then forgive me but at least please have a look at the change and try to find a problem.

I would test pm2 with this reverted but not sure how to force older version of this package when pm2 is installed locally...

**Comment by rchl** [comment]
I've now confirmed locally that reverting to `@pm2/io@4.2.0` fixes the "leak" so there must be something wrong with this fix.

**Comment by KillianCarroll** [comment]
I'm seeing the same memory leak. It looks like someone spotted it previously.

https://github.com/keymetrics/pm2-io-apm/issues/252

**Comment by rchl** [comment]
@KillianCarroll I don't know if it's the same issue as it references file that wasn't modified here but it very well could be.

ping @Unitech

**Comment by Eywek** [comment]
Can you try with https://github.com/keymetrics/pm2-io-apm/releases/tag/4.2.2 ?

**Comment by Unitech** [comment]
cc https://github.com/Unitech/pm2/issues/4302

**Comment by rchl** [comment]
@Eywek @Unitech seems fine with 4.2.2. No increasing CPU or memory usage after 12 hours.

**Comment by Eywek** [comment]
Thanks!
