### ISSUE TITLE
User process.on('uncaughtException') not called with pm2-io-apm

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#253]
https://github.com/Unitech/pm2/issues/4298

**Comment by Eywek** [comment]
> You can set `catchExceptions` option to false to handle errors yourself

**Comment by Unitech** [comment]
ok it somewhat fix this issue, but with pmx, users could set their own event handler for exception and we were auto detecting it.

We have to restore this automatic logic into pm2-io-apm
https://github.com/keymetrics/pmx/blob/fbb910f6a473ba1b821c66c673c776d851b575ac/lib/notify.js#L70
