### ISSUE TITLE
Not a drop in replacement?

### ISSUE THREAD

**Issue by bradennapier** [keymetrics/pm2-io-apm#255]
This says that `@pm2/io` is a drop-in replacement but i see a bunch of differences at first glance.  No `ports`, metrics moved to `metrics` property....

`pmx.init({ network: true, ports: true })` is not `pmx.init({ metrics: { network: true } })` and it looks like `ports` is not an option at all.

**Comment by bradennapier** [comment]
Additionally this doesnt work...

```
/** Track how many connected websockets are currently active. */
const connectedUsers = pmx.probe().metric({
  name: 'Connected Clients',
});
```

you should fix the info and provide a migration doc

**Comment by Eywek** [comment]
You can find migration guide here https://github.com/keymetrics/pm2-io-apm#migration-guides. I've updated it for the `probe()` method removed [here](https://github.com/keymetrics/pm2-io-apm/commit/27b22724334cbe9e2b01e60a571c865b2f3aea26)
