### ISSUE TITLE
HTTP Metric not displaying correct values

### ISSUE THREAD

**Issue by DeltaCore** [keymetrics/pm2-io-apm#256]
Hello.

I tried to use the `@pm2/io` package to monitor my express instance.

I had made an interval of 10sec to fetch some data from that express instance. 
When i used pm2 describe on my process, this is what i got:

![Screenshot_46](https://user-images.githubusercontent.com/5575913/60083920-dfc88780-9736-11e9-93e0-002f2ba9618f.png)

Naturally i expected that the metric HTTP which has the unit req/min - requests per minute to be somewhere around 6.
But it always was 0.1.

I made a little test which i tested on multiple versions of node and got everywhere the same result.
Link to the git repo: https://git.ccmob.net/marcel/pm2-metric-test

Am i missing somehthing here or is that the correct behavior?
If there is anything i can help with, let me know.

Best Regards,
Marcel

**Comment by Unitech** [comment]
This is the expected behavior, basically the calculation is a request rate
