### ISSUE TITLE
Latest version (5.0.1) committed not tagged/released

### ISSUE THREAD

**Issue by johnal95** [keymetrics/pm2-io-apm#294]
Hey @Unitech, hope you are well.

I noticed the latest version (5.0.1) committed in this project was not tagged/published, and was wondering if that was intentional.

**Comment by theuniverse** [comment]
I will really appreciate if anyone in the maintenance team can help releash 5.0.1 as it's related to a vulnerability of high severity. :)

**Comment by OIRNOIR** [comment]
I would like to second this issue. I just noticed the same thing.

**Comment by rohanmishra0396** [comment]
Hi @Unitech,

It will be great if you can help to publish this version (5.0.1).

**Comment by DiracSpace** [comment]
@Unitech We really need this published.

**Comment by Unitech** [comment]
The thing is that I have not built this module and I there are issues running the `npm run build` command...
If anyone has experience on this and can try to make this module compile again, please send a PR

**Comment by OIRNOIR** [comment]
> The thing is that I have not built this module and there are issues running the `npm run build` command...
> If anyone has experience on this and can try to make this module compile again, please send a PR

This might be the case because @pm2/node-runtime-stats depends upon a very old version of node-gyp which no longer works with modern python versions.

**Comment by OIRNOIR** [comment]
> The thing is that I have not built this module and there are issues running the `npm run build` command...
> If anyone has experience on this and can try to make this module compile again, please send a PR

What do you think of this? https://github.com/keymetrics/pm2-io-apm/pull/297

**Comment by OIRNOIR** [comment]
@johnal95 This issue can be closed as a fixed version (5.0.2) has been released and tagged.

**Comment by johnal95** [comment]
Many thanks @OIRNOIR, closing the issue.
