### ISSUE TITLE
Feature: tracing system: allow for custom tracing system

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-apm#9]
Some people need to create custom tracing (example they process queries via websocket instead of http)

## GCP Stack driver

e.g.: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#custom-tracing-api

## APM Elasticsearch

https://www.elastic.co/guide/en/apm/agent/nodejs/current/custom-spans.html

## AppDynamics

https://docs.appdynamics.com/display/PRO43/Node.js+Agent+API+Reference#Node.jsAgentAPIReference-txn.addAnalyticsData(key,value)

**Comment by Unitech** [comment]
const pmx = require('@pm2/io');

**Comment by vmarchaud** [comment]
Closing in favor of https://github.com/keymetrics/pm2-io-apm/issues/204
